#App setup
database: ..\..\repository\database\notifyDB.db #Your database file directory
linenotifyUrl: https://notify-api.line.me/api/notify

#Notification time
dailyNotiTime: "10:00:00" #Time you want to get daily task from line notification
weeklyNotiDate: "Monday" #Day of week you want to get weekly tasks from line notification
weeklyNotiTime: "10:00:00" #Time you want to get weekly task from line notification
